import "../style/global.css"
import Nav from "../components/nav/page"
import CreateBtn from "../components/CreateBtn/page"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <CreateBtn />
      </body>
    </html>
  )
}
